spring:
 datasource:
  driver-class-name: org.sqlite.JDBC
  username: ''
  password: ''
  url: jdbc:sqlite:housedata.sqlite

sql:
 init:
  schema-locations: classpath:db/schema-h2.sql
  data-locations: classpath:db/data-h2.sql
